POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name":"hello",
  "username":"tongnamuu@gmail.com",
  "password":"Password123",
  "isParticipant": true,
  "email": "hello@naver.com",
  "gender": "Male",
  "birthday": "10102211"
}
